# -- coding: utf-8 --

# Form implementation generated from reading ui file 'buyerform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import mysql.connector as c
import random


con = c.connect(
    host=" localhost", user=" root", passwd="password", database="dbms_project_2"
)
cursor = con.cursor()


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1366, 700)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 1361, 701))
        self.label.setStyleSheet(
            "background:url(:/buyer/Users/hp/Downloads/20 Spendid Purple Backgrounds for Free Download Free.jpg)"
        )
        self.label.setText("")
        self.label.setPixmap(
            QtGui.QPixmap(":/images/WhatsApp Image 2023-04-03 at 12.52.18.jpeg")
        )
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(60, 90, 981, 611))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}QLabel\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(80, 80, 961, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(
            "QLabel\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:black;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(180, 230, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(180, 250, 661, 25))
        self.lineEdit.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(180, 280, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Frame)
        self.comboBox.setGeometry(QtCore.QRect(190, 300, 92, 25))
        self.comboBox.setStyleSheet(
            "QComboBox\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 300, 311, 25))
        self.lineEdit_2.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(180, 350, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 380, 661, 25))
        self.lineEdit_3.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(180, 520, 141, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setGeometry(QtCore.QRect(200, 550, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 570, 461, 25))
        self.lineEdit_4.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Frame)
        self.label_9.setGeometry(QtCore.QRect(200, 600, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 620, 321, 25))
        self.lineEdit_5.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setGeometry(QtCore.QRect(610, 600, 121, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(610, 620, 311, 25))
        self.lineEdit_6.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(Frame)
        self.label_11.setGeometry(QtCore.QRect(740, 280, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.radioButton = QtWidgets.QRadioButton(Frame)
        self.radioButton.setGeometry(QtCore.QRect(740, 300, 119, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Frame)
        self.radioButton_2.setGeometry(QtCore.QRect(850, 300, 119, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(500, 650, 112, 34))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(
            "QPushButton{\n"
            "background:rgb(74, 0, 112);\n"
            "border-radius:15%;\n"
            "color:#fff;\n"
            "}\n"
            "QPushButton:hover{\n"
            "background:rgb(156, 78, 234);\n"
            "border-radius:15%;\n"
            "}\n"
            "QPushButton:pressed{  padding-left:5px;\n"
            "  padding-top:5px;\n"
            "  background-color:rgba(105, 118, 132, 200);\n"
            "}"
        )
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_7 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 450, 321, 25))
        self.lineEdit_7.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 200, 191, 25))
        self.lineEdit_8.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(710, 450, 281, 25))
        self.lineEdit_9.setStyleSheet(
            "QLineEdit\n"
            "{\n"
            "background:rgb(225, 225, 225,100);\n"
            "border:none;\n"
            "color:#717072;\n"
            "\n"
            "border-radius:15%;\n"
            "}"
        )
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_13 = QtWidgets.QLabel(Frame)
        self.label_13.setGeometry(QtCore.QRect(190, 430, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Frame)
        self.label_14.setGeometry(QtCore.QRect(180, 180, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Frame)
        self.label_15.setGeometry(QtCore.QRect(710, 430, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_12 = QtWidgets.QLabel(Frame)
        self.label_12.setGeometry(QtCore.QRect(1040, 80, 301, 231))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap(":/images/Picture1-removebg-preview.png"))
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

        self.pushButton.clicked.connect(self.register())

    def register(self):
        name = self.lineEdit.text()
        contact = self.lineEdit_2.text()
        if self.radioButton.isChecked():
            mode = "SOLD"
        else:
            mode = "Rented"
        email_id = self.lineEdit_3.text()
        address_line_1 = self.lineEdit_4.text()
        address_line_2 = self.lineEdit_5.text()
        address_line_3 = self.lineEdit_6.text()
        p_id = self.lineEdit_7.text()
        buyer_id = self.lineEdit_8.text()
        date = self.lineEdit_9.text()

        agent_id = {5, 7, 13, 17, 18, 21, 28, 30, 31, 33, 35, 37, 38, 39, 40}
        emp_id = random.choice(list(agent_id))
        query_add_buyer = f"INSERT INTO buyer (emp_id,name,email_id,contact,address_line_1,address_line_2,address_line_3) VALUES ({emp_id}, {name}, {email_id}, {contact},{address_line_1},{address_line_2},{address_line_3})"
        cursor.execute(query_add_buyer)
        con.commit()

        query_update_mode = f"UPDATE property SET mode = {mode} WHERE p_id = {p_id}"
        cursor.execute(query_update_mode)
        con.commit()

        query_add_status = f"INSERT INTO status (p_id, buyer_id, emp_ID_buyer, date) VALUES ({p_id}, {buyer_id}, {agent_id}, {date})"
        cursor.execute(query_add_status)
        if cursor.rowcount > 0:
            self.label_16 = QtWidgets.QLabel(Frame)
            self.label_16.setGeometry(QtCore.QRect(690, 670, 55, 16))
            self.label_16.setText("")
            self.label_16.setObjectName("label_16")
            self.label_16.setText("Registration successfull")
        else:
            self.label_16 = QtWidgets.QLabel(Frame)
            self.label_16.setGeometry(QtCore.QRect(690, 670, 55, 16))
            self.label_16.setText("")
            self.label_16.setObjectName("label_16")
            self.label_16.setText("Try again!")
        con.commit()

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_3.setText(
            _translate(
                "Frame",
                "                                                  BUYER DETAILS",
            )
        )
        self.label_4.setText(_translate("Frame", "Name"))
        self.label_5.setText(_translate("Frame", "Contact"))
        self.comboBox.setItemText(0, _translate("Frame", "IND +91"))
        self.label_6.setText(_translate("Frame", "Email-ID"))
        self.label_7.setText(_translate("Frame", "Address:"))
        self.label_8.setText(_translate("Frame", "Street"))
        self.label_9.setText(_translate("Frame", "Area"))
        self.label_10.setText(_translate("Frame", "Part Of Delhi"))
        self.label_11.setText(_translate("Frame", "Mode"))
        self.radioButton.setText(_translate("Frame", "BUY"))
        self.radioButton_2.setText(_translate("Frame", "RENT"))
        self.pushButton.setText(_translate("Frame", "REGISTER"))
        self.label_13.setText(_translate("Frame", "P_ID"))
        self.label_14.setText(_translate("Frame", "BUYER_ID"))
        self.label_15.setText(_translate("Frame", "Date Of Sell(YYYY-MM-DD)"))


import form2_rc
import res_rc


if __name__ == "_main_":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())

con.close()
