# -*- coding: utf-8 -*-
import re
# Form implementation generated from reading ui file 'buyerform.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
import traceback
from datetime import datetime

from PyQt5.QtGui import QIntValidator


class Buyer_Frame(object):
    userID = ""

    def __init__(self, x):
        self.userID = x

    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1386, 729)
        Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setGeometry(QtCore.QRect(0, -10, 1391, 741))
        self.label.setStyleSheet(
            "background:url(:/buyer/Users/hp/Downloads/20 Spendid Purple Backgrounds for Free Download Free.jpg)")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/background.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 981, 611))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("*{\n"
                                   "background:rgb(150,150,150,100);\n"
                                   "border:none;\n"
                                   "color:#464646;\n"
                                   "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                   "border-radius:15%;\n"
                                   "}\n"
                                   "QLineEdit\n"
                                   "{\n"
                                   "background:rgb(150,150,150,100);\n"
                                   "border:none;\n"
                                   "color:#464646;\n"
                                   "font weight: bold;\n"
                                   "border-radius:15%;\n"
                                   "}QLabel\n"
                                   "{\n"
                                   "background:rgb(180, 180, 180,100);\n"
                                   "border:none;\n"
                                   "color:#717072;\n"
                                   "\n"
                                   "border-radius:15%;\n"
                                   "}\n"
                                   "")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Frame)
        self.label_3.setGeometry(QtCore.QRect(70, 80, 981, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
                                   "{\n"
                                   "background:rgb(225, 225, 225,100);\n"
                                   "border:none;\n"
                                   "color:black;\n"
                                   "\n"
                                   "border-radius:15%;\n"
                                   "}\n"
                                   "#label_3\n"
                                   "{\n"
                                   "background: rgba(150,150,150,0.8)\n"
                                   "}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Frame)
        self.label_4.setGeometry(QtCore.QRect(180, 230, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Frame)
        self.lineEdit.setGeometry(QtCore.QRect(180, 250, 751, 25))
        self.lineEdit.setStyleSheet("\n"
                                    "\n"
                                    "\n"
                                    "background:rgb(150,150,150,100);\n"
                                    "border:none;\n"
                                    "color:#464646;\n"
                                    "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                    "border-radius:15%;\n"
                                    "")
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(Frame)
        self.label_5.setGeometry(QtCore.QRect(180, 280, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(Frame)
        self.comboBox.setGeometry(QtCore.QRect(180, 300, 92, 25))
        self.comboBox.setStyleSheet("background:rgb(150,150,150,100);\n"
                                    "border:none;\n"
                                    "color:#464646;\n"
                                    "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                    "border-radius:15%;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.lineEdit_2 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(300, 300, 311, 25))
        self.lineEdit_2.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(Frame)
        self.label_6.setGeometry(QtCore.QRect(180, 330, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 360, 661, 25))
        self.lineEdit_3.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(Frame)
        self.label_7.setGeometry(QtCore.QRect(180, 460, 141, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Frame)
        self.label_8.setGeometry(QtCore.QRect(200, 500, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 520, 461, 25))
        self.lineEdit_4.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(Frame)
        self.label_9.setGeometry(QtCore.QRect(200, 560, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 580, 321, 25))
        self.lineEdit_5.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(Frame)
        self.label_10.setGeometry(QtCore.QRect(690, 550, 121, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_6 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(690, 580, 311, 25))
        self.lineEdit_6.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_11 = QtWidgets.QLabel(Frame)
        self.label_11.setGeometry(QtCore.QRect(740, 280, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.radioButton = QtWidgets.QRadioButton(Frame)
        self.radioButton.setGeometry(QtCore.QRect(740, 300, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons8-list-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton.setIcon(icon)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(Frame)
        self.radioButton_2.setGeometry(QtCore.QRect(850, 300, 121, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/building-user-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.radioButton_2.setIcon(icon1)
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(Frame)
        self.pushButton.setGeometry(QtCore.QRect(460, 620, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "background:rgb(74, 0, 112);\n"
                                      "border-radius:15%;\n"
                                      "color:#fff;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "background:rgb(156, 78, 234);\n"
                                      "border-radius:15%;\n"
                                      "}\n"
                                      "QPushButton:pressed{  padding-left:5px;\n"
                                      "  padding-top:5px;\n"
                                      "  background-color:rgba(105, 118, 132, 200);\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_7 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 420, 321, 25))
        self.lineEdit_7.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_8.setGeometry(QtCore.QRect(180, 200, 191, 25))
        self.lineEdit_8.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(Frame)
        self.lineEdit_9.setGeometry(QtCore.QRect(690, 430, 281, 25))
        self.lineEdit_9.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_13 = QtWidgets.QLabel(Frame)
        self.label_13.setGeometry(QtCore.QRect(180, 400, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Frame)
        self.label_14.setGeometry(QtCore.QRect(180, 180, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Frame)
        self.label_15.setGeometry(QtCore.QRect(690, 410, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Frame)
        self.label_16.setGeometry(QtCore.QRect(690, 630, 311, 41))
        self.label_16.setStyleSheet("\n"
                                    "background:rgb(150,150,150,100);\n"
                                    "border:none;\n"
                                    "color:red;\n"
                                    "font: 75 12pt \"MS Shell Dlg 2\";\n"
                                    "border-radius:15%;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_12 = QtWidgets.QLabel(Frame)
        self.label_12.setGeometry(QtCore.QRect(1040, -40, 361, 251))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("realtor_02-removebg-preview.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def register(self):
        global date
        # # p = 1
        # b = 1
        d = 1
        safe = 1
        c = 1
        safe2 = 1
        name = self.lineEdit.text()
        contact = self.lineEdit_2.text()

        if (len(contact) != 10 and type(contact != int)):
            # self.label_16.setText("enter 10 digit integer")
            safe = 0
        mode = ""
        if self.radioButton.isChecked():
            mode = "Sold"
        elif self.radioButton_2.isChecked():
            mode = "Rented"
        else:
            self.label_16.setText("Select BUY/RENT")

        email_id = self.lineEdit_3.text()
        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
        if re.fullmatch(regex, email_id):
            safe1 = 1
        else:
            safe1 = 0
        address_line_1 = self.lineEdit_4.text()
        address_line_2 = self.lineEdit_5.text()
        address_line_3 = self.lineEdit_6.text()
        p_id = 0
        if len(self.lineEdit_7.text()) == 0:
            c = 0
        else:
            p_id = int(self.lineEdit_7.text())
        buyer_id = 0
        if len(self.lineEdit_8.text()) == 0:
            safe2 = 0
        else:
            buyer_id = int(self.lineEdit_8.text())
            onlyInt = QIntValidator()
            self.lineEdit_8.setValidator(onlyInt)
        # if type(buyer_id) != int:
        #     b = 0
        # if type(p_id) != int:
        #     p = 0
        date_string = self.lineEdit_9.text()
        if len(date_string) != 0:
            try:
                date = datetime.strptime(date_string, "%Y-%m-%d")
                if date > date.today():
                    d = 0
            except:
                d = 0
                self.label_16.setText("INVALID DATE FORMAT!")

        if len(name) != 0 and len(contact) != 0 and len(mode) != 0 and len(email_id) != 0 and len(
                address_line_1 + address_line_2 + address_line_3) != 0 and safe == 1 and len(
            date_string) != 0 and d == 1 and safe2 == 1 and c == 1 and safe1 == 1:
            print("Inside if")
            try:
                mydb = mc.connect(
                    host="localhost",
                    user="root",
                    password="Yash@2914",
                    database="dbms_project"
                )
                cursor = mydb.cursor()
                emp_id = self.userID  # int(self.userID)
                query = "SELECT mode from property where p_id = {}".format(p_id)
                cursor.execute(query)
                result = cursor.fetchone()
                print(result[0])
                if result[0] != 'Sold' and result[0] != 'Rented':
                    if result[0] == 'S' and mode == 'Sold' or result[0] == 'R' and mode == 'Rented' or result[
                        0] == 'RS':

                        query_add_buyer = "INSERT INTO buyer (buyer_id, emp_id,name,email_id,contact,address_line_1,address_line_2,address_line_3) VALUES (%s,%s, %s, %s, %s, %s, %s, %s)"
                        cursor.execute(query_add_buyer, (
                            int(buyer_id), emp_id, name, email_id, contact, address_line_1, address_line_2,
                            address_line_3))
                        mydb.commit()

                        query_update_mode = "UPDATE property SET mode = %s WHERE p_id = %s"
                        cursor.execute(query_update_mode, (mode, p_id))
                        mydb.commit()

                        query_add_status = "INSERT INTO status (p_id, buyer_id, emp_ID_buyer, date) VALUES (%s, %s, %s, %s)"
                        cursor.execute(query_add_status, (int(p_id), int(buyer_id), emp_id, date))
                        if cursor.rowcount > 0:
                            self.label_16.setText("Registration successful")
                        else:
                            self.label_16.setText("Try again!")
                        mydb.commit()
                    else:
                        self.label_16.setText("CHOOSEN MODE IS WRONG!")
                else:
                    self.label_16.setText("Property Not Available!")



            except mc.Error as e:
                traceback.print_exc()
                self.label_16.setText("INVALID INPUT!")

        else:

            self.label_16.setText("ENTER ALL VALID INPUTS!")

            # self.label_16.setText("ENTER 10 digit integer!")

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label_3.setText(_translate("Frame",
                                        "                                                                        BUYER DETAILS"))
        self.label_4.setText(_translate("Frame", "Name"))
        self.label_5.setText(_translate("Frame", "Contact"))
        self.comboBox.setItemText(0, _translate("Frame", "IND +91"))
        self.label_6.setText(_translate("Frame", "Email-ID"))
        self.label_7.setText(_translate("Frame", "Address:"))
        self.label_8.setText(_translate("Frame", "Street"))
        self.label_9.setText(_translate("Frame", "Area"))
        self.label_10.setText(_translate("Frame", "Part Of Delhi"))
        self.label_11.setText(_translate("Frame", "Mode"))
        self.radioButton.setText(_translate("Frame", "BUY"))
        self.radioButton_2.setText(_translate("Frame", "RENT"))
        self.pushButton.setText(_translate("Frame", "REGISTER"))
        self.label_13.setText(_translate("Frame", "P_ID"))
        self.label_14.setText(_translate("Frame", "BUYER_ID"))
        self.label_15.setText(_translate("Frame", "Date Of Sale(YYYY-MM-DD)"))


import form_rc
import res_rc

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Frame = QtWidgets.QFrame()
#     ui = Buyer_Frame()
#     ui.setupUi(Frame)
#     Frame.show()
#     sys.exit(app.exec_())
