# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'as.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from datetime import date as date1
import re

from PyQt5.QtGui import QIntValidator

year = ""
from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
import traceback

from PyQt5 import QtCore, QtGui, QtWidgets


class seller_TabWidget(object):
    userID = ""

    def __init__(self, x):
        self.userID = x

    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1657, 771)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 601, 731))
        self.label.setStyleSheet("background:#fff;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(370, 140, 191, 161))
        self.label_2.setStyleSheet("background:url(:/form/Downloads/WhatsApp Image 2023-04-03 at 12.59.14.jpeg)")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/form/Downloads/WhatsApp Image 2023-04-03 at 12.59.14.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(0, -30, 1651, 801))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
                                   "background:url(:/newPrefix/Downloads/WhatsApp Image 2023-04-03 at 12.52.18.jpeg)\n"
                                   "}")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/images/background.jpeg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(1170, 130, 321, 411))
        self.label_4.setStyleSheet("QLabel{\n"
                                   "\n"
                                   "background:rgb(225, 225, 225,100);\n"
                                   "border:none;\n"
                                   "color:#717072;\n"
                                   "border-bottom:1px solid #717072;\n"
                                   "border-radius:15%;\n"
                                   "}")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(1320, 150, 171, 111))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit\n"
                                    "{\n"
                                    "background:transparent;\n"
                                    "border:none;\n"
                                    "color:#717072;\n"
                                    "border-bottom:1px solid #717072;\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(1180, 260, 161, 111))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit\n"
                                      "{\n"
                                      "background:transparent;\n"
                                      "border:none;\n"
                                      "color:#717072;\n"
                                      "border-bottom:1px solid #717072;\n"
                                      "border-radius:15%;\n"
                                      "}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(660, 0, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(680, 30, 321, 19))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(930, 30, 41, 21))
        self.label_7.setStyleSheet("QLabel{\n"
                                   "background:rgb(181, 181, 0);\n"
                                   "border-radius:15%;\n"
                                   "}")
        self.label_7.setObjectName("label_7")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(210, 330, 301, 41))
        self.label_11.setStyleSheet("QLabel{\n"
                                    "background:rgb(232, 235, 199);\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(210, 360, 301, 21))
        self.label_12.setStyleSheet("QLabel{\n"
                                    "background:rgb(232, 235, 199)\n"
                                    "}")
        self.label_12.setObjectName("label_12")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.tab)
        self.commandLinkButton.setGeometry(QtCore.QRect(130, 690, 161, 41))
        self.commandLinkButton.setStyleSheet("QPushButton{\n"
                                             "background:rgb(74, 0, 112);\n"
                                             "border-radius:15%;\n"
                                             "color:#fff;\n"
                                             "}\n"
                                             "QPushButton:hover{\n"
                                             "background:rgb(156, 78, 234);\n"
                                             "border-radius:15%;\n"
                                             "}")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(1200, 180, 91, 91))
        self.label_16.setStyleSheet("background:url(:/Downloads/customer-service.png)")
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/images/customer-service.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(1360, 290, 101, 91))
        self.label_17.setStyleSheet("background:url(:/Downloads/profile.png)")
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap(":/images/profile.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(1170, 130, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background:rgb(228, 228, 228);\n"
                                    "bordrer-radius : 15%;")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(1230, 430, 101, 81))
        self.label_19.setStyleSheet("background:url(:/newPrefix/Downloads/signboard.png)")
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap(":/images/signboard.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(1330, 420, 111, 91))
        self.label_20.setStyleSheet("background:url(:/form/Downloads/present.png)")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap(":/images/present.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(1360, 220, 81, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(1190, 330, 141, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_38 = QtWidgets.QLabel(self.tab)
        self.label_38.setGeometry(QtCore.QRect(100, 70, 1001, 601))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("QLabel\n"
                                    "{\n"
                                    "background:rgb(150, 150,150,100);\n"
                                    "border:none;\n"
                                    "color:#717072;\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.label_41 = QtWidgets.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(190, 190, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 210, 751, 25))
        self.lineEdit_5.setStyleSheet("QLineEdit\n"
                                      "{\n"
                                      "background:rgb(150, 150, 150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;\n"
                                      "}")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(190, 260, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(190, 280, 92, 25))
        self.comboBox.setStyleSheet("QLineEdit\n"
                                    "{\n"
                                    "background:rgb(150, 150, 150,100);\n"
                                    "border:none;\n"
                                    "color:#464646;\n"
                                    "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_6.setGeometry(QtCore.QRect(300, 280, 241, 25))
        self.lineEdit_6.setStyleSheet("QLineEdit\n"
                                      "{\n"
                                      "background:rgb(150, 150, 150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;\n"
                                      "}")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(190, 410, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_14.setGeometry(QtCore.QRect(190, 440, 751, 25))
        self.lineEdit_14.setStyleSheet("QLineEdit\n"
                                       "{\n"
                                       "background:rgb(150, 150, 150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;\n"
                                       "}")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(190, 500, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_15.setGeometry(QtCore.QRect(200, 570, 331, 25))
        self.lineEdit_15.setStyleSheet("QLineEdit\n"
                                       "{\n"
                                       "background:rgb(150, 150, 150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;\n"
                                       "}")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_42 = QtWidgets.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(200, 540, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.tab)
        self.label_43.setGeometry(QtCore.QRect(590, 540, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_16.setGeometry(QtCore.QRect(590, 570, 191, 25))
        self.lineEdit_16.setStyleSheet("QLineEdit\n"
                                       "{\n"
                                       "background:rgb(150, 150, 150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;\n"
                                       "}")
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.label_44 = QtWidgets.QLabel(self.tab)
        self.label_44.setGeometry(QtCore.QRect(830, 540, 111, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_17.setGeometry(QtCore.QRect(830, 570, 241, 25))
        self.lineEdit_17.setStyleSheet("QLineEdit\n"
                                       "{\n"
                                       "background:rgb(150, 150, 150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 9pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;\n"
                                       "}")
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(100, 70, 1001, 51))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(161, 161, 161);\n"
                                   "border:none;\n"
                                   "color:black;\n"
                                   "border-radius:15%;")
        self.label_8.setObjectName("label_8")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(720, 240, 211, 191))
        self.label_15.setStyleSheet("QLabel\n"
                                    "{\n"
                                    "background:rgb(225, 225, 225,100);\n"
                                    "\n"
                                    "\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("realtor-removebg-preview.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_23 = QtWidgets.QLabel(self.tab)
        self.label_23.setGeometry(QtCore.QRect(740, 690, 251, 16))
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/user-tie-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.addTab(self.tab, icon, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.label_24 = QtWidgets.QLabel(self.tab1)
        self.label_24.setGeometry(QtCore.QRect(-10, -10, 1671, 751))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background:url(:/newPrefix/Downloads/WhatsApp Image 2023-04-03 at 12.52.18.jpeg)")
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/images/background.jpeg"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab1)
        self.label_25.setGeometry(QtCore.QRect(1220, 100, 381, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("QLabel\n"
                                    "{\n"
                                    "background:rgb(225, 225, 225,100);\n"
                                    "border:none;\n"
                                    "color:#717072;\n"
                                    "border-bottom:1px solid #717072;\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab1)
        self.label_26.setGeometry(QtCore.QRect(1220, 120, 61, 61))
        self.label_26.setStyleSheet("background:url(:/house/Downloads/icons8-list-64.png)")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_7.setGeometry(QtCore.QRect(1220, 100, 381, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("QLineEdit\n"
                                      "{\n"
                                      "background:rgb(225, 225, 225,100);\n"
                                      "border:none;\n"
                                      "\n"
                                      "text-color:black;\n"
                                      "\n"
                                      "border-radius:15%;\n"
                                      "}")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_27 = QtWidgets.QLabel(self.tab1)
        self.label_27.setGeometry(QtCore.QRect(50, 50, 1131, 591))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("QPushButton\n"
                                    "{\n"
                                    "background:rgb(150, 150, 150,100);\n"
                                    "border:none;\n"
                                    "color:#717072;\n"
                                    "border-bottom:1px solid #717072;\n"
                                    "border-radius:15%;\n"
                                    "}\n"
                                    "QPushButton:hover{   \n"
                                    "  background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop:1 rgba(105, 118, 132, 226));\n"
                                    "}\n"
                                    "QPushButton:pressed{  padding-left:5px;\n"
                                    "  padding-top:5px;\n"
                                    "  background-color:rgba(105, 118, 132, 200);\n"
                                    "}QLabel\n"
                                    "{\n"
                                    "background:rgb(225, 225, 225,100);\n"
                                    "border:none;\n"
                                    "color:#717072;\n"
                                    "\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_8.setGeometry(QtCore.QRect(50, 50, 1131, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("background:rgb(100,100,100,100);\n"
                                      "border:none;\n"
                                      "color:black;\n"
                                      "border-radius:15%;\n"
                                      "\n"
                                      "font: 18pt \"MS Shell Dlg 2\";\n"
                                      "")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 280, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "background:rgb(74, 0, 112);\n"
                                        "border-radius:15%;\n"
                                        "color:#fff;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background:rgb(156, 78, 234);\n"
                                        "border-radius:15%;\n"
                                        "}\n"
                                        "QPushButton:pressed{  padding-left:5px;\n"
                                        "  padding-top:5px;\n"
                                        "  background-color:rgba(105, 118, 132, 200);\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_5.setGeometry(QtCore.QRect(230, 280, 151, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "background:rgb(74, 0, 112);\n"
                                        "border-radius:15%;\n"
                                        "color:#fff;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background:rgb(156, 78, 234);\n"
                                        "border-radius:15%;\n"
                                        "}\n"
                                        "QPushButton:pressed{  padding-left:5px;\n"
                                        "  padding-top:5px;\n"
                                        "  background-color:rgba(105, 118, 132, 200);\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_6.setGeometry(QtCore.QRect(790, 280, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "background:rgb(74, 0, 112);\n"
                                        "border-radius:15%;\n"
                                        "color:#fff;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background:rgb(156, 78, 234);\n"
                                        "border-radius:15%;\n"
                                        "}\n"
                                        "QPushButton:pressed{  padding-left:5px;\n"
                                        "  padding-top:5px;\n"
                                        "  background-color:rgba(105, 118, 132, 200);\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 280, 151, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                        "background:rgb(74, 0, 112);\n"
                                        "border-radius:15%;\n"
                                        "color:#fff;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background:rgb(156, 78, 234);\n"
                                        "border-radius:15%;\n"
                                        "}\n"
                                        "QPushButton:pressed{  padding-left:5px;\n"
                                        "  padding-top:5px;\n"
                                        "  background-color:rgba(105, 118, 132, 200);\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_8.setGeometry(QtCore.QRect(550, 280, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
                                        "background:rgb(74, 0, 112);\n"
                                        "border-radius:15%;\n"
                                        "color:#fff;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background:rgb(156, 78, 234);\n"
                                        "border-radius:15%;\n"
                                        "}\n"
                                        "QPushButton:pressed{  padding-left:5px;\n"
                                        "  padding-top:5px;\n"
                                        "  background-color:rgba(105, 118, 132, 200);\n"
                                        "}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_9.setGeometry(QtCore.QRect(670, 280, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "background:rgb(74, 0, 112);\n"
                                        "border-radius:15%;\n"
                                        "color:#fff;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background:rgb(156, 78, 234);\n"
                                        "border-radius:15%;\n"
                                        "}\n"
                                        "QPushButton:pressed{  padding-left:5px;\n"
                                        "  padding-top:5px;\n"
                                        "  background-color:rgba(105, 118, 132, 200);\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 370, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
                                         "background:rgb(74, 0, 112);\n"
                                         "border-radius:15%;\n"
                                         "color:#fff;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "background:rgb(156, 78, 234);\n"
                                         "border-radius:15%;\n"
                                         "}\n"
                                         "QPushButton:pressed{  padding-left:5px;\n"
                                         "  padding-top:5px;\n"
                                         "  background-color:rgba(105, 118, 132, 200);\n"
                                         "}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_9.setGeometry(QtCore.QRect(120, 560, 421, 25))
        self.lineEdit_9.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_10.setGeometry(QtCore.QRect(570, 560, 221, 25))
        self.lineEdit_10.setStyleSheet("background:rgb(150,150,150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;")
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_11.setGeometry(QtCore.QRect(820, 560, 231, 25))
        self.lineEdit_11.setStyleSheet("background:rgb(150,150,150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;")
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab1)
        self.comboBox_2.setGeometry(QtCore.QRect(730, 380, 141, 25))
        self.comboBox_2.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_12.setGeometry(QtCore.QRect(100, 450, 461, 25))
        self.lineEdit_12.setStyleSheet("background:rgb(150,150,150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;")
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_28 = QtWidgets.QLabel(self.tab1)
        self.label_28.setGeometry(QtCore.QRect(100, 170, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab1)
        self.label_29.setGeometry(QtCore.QRect(100, 250, 131, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab1)
        self.label_30.setGeometry(QtCore.QRect(100, 340, 68, 20))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.tab1)
        self.label_31.setGeometry(QtCore.QRect(730, 350, 191, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab1)
        self.label_32.setGeometry(QtCore.QRect(120, 540, 91, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.tab1)
        self.label_33.setGeometry(QtCore.QRect(570, 540, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.tab1)
        self.label_34.setGeometry(QtCore.QRect(820, 540, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab1)
        self.pushButton_14.setGeometry(QtCore.QRect(530, 660, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
                                         "background:rgb(74, 0, 112);\n"
                                         "border-radius:15%;\n"
                                         "color:#fff;\n"
                                         "}\n"
                                         "QPushButton:hover{\n"
                                         "background:rgb(156, 78, 234);\n"
                                         "border-radius:15%;\n"
                                         "}\n"
                                         "QPushButton:pressed{  padding-left:5px;\n"
                                         "  padding-top:5px;\n"
                                         "  background-color:rgba(105, 118, 132, 200);\n"
                                         "}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_35 = QtWidgets.QLabel(self.tab1)
        self.label_35.setGeometry(QtCore.QRect(100, 430, 68, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab1)
        self.label_36.setGeometry(QtCore.QRect(100, 510, 101, 19))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.tab1)
        self.label_37.setGeometry(QtCore.QRect(1220, 240, 371, 351))
        self.label_37.setStyleSheet("QLabel\n"
                                    "{\n"
                                    "background:rgb(225, 225, 225,100);\n"
                                    "border:none;\n"
                                    "color:#717072;\n"
                                    "\n"
                                    "border-radius:15%;\n"
                                    "}")
        self.label_37.setObjectName("label_37")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_13.setGeometry(QtCore.QRect(1230, 240, 361, 25))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("QLineEdit\n"
                                       "{\n"
                                       "background:rgb(225, 225, 225,100);\n"
                                       "border:none;\n"
                                       "color:black;\n"
                                       "\n"
                                       "border-radius:15%;\n"
                                       "}")
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_4.setGeometry(QtCore.QRect(110, 200, 119, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_5.setGeometry(QtCore.QRect(250, 200, 119, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_6.setGeometry(QtCore.QRect(410, 200, 119, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_6.setFont(font)
        self.radioButton_6.setObjectName("radioButton_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_3.setGeometry(QtCore.QRect(600, 450, 451, 25))
        self.lineEdit_3.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_9 = QtWidgets.QLabel(self.tab1)
        self.label_9.setGeometry(QtCore.QRect(1210, 240, 351, 351))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("houseon_rent-removebg-preview.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_48 = QtWidgets.QLabel(self.tab1)
        self.label_48.setGeometry(QtCore.QRect(940, 350, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet("")
        self.label_48.setObjectName("label_48")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_4.setGeometry(QtCore.QRect(920, 281, 231, 31))
        self.lineEdit_4.setStyleSheet("background:rgb(150,150,150,100);\n"
                                      "border:none;\n"
                                      "color:#464646;\n"
                                      "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                      "border-radius:15%;")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_19.setGeometry(QtCore.QRect(230, 371, 391, 31))
        self.lineEdit_19.setStyleSheet("background:rgb(150,150,150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;")
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab1)
        self.lineEdit_21.setGeometry(QtCore.QRect(930, 380, 221, 22))
        self.lineEdit_21.setStyleSheet("background:rgb(150,150,150,100);\n"
                                       "border:none;\n"
                                       "color:#464646;\n"
                                       "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                       "border-radius:15%;")
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_39 = QtWidgets.QLabel(self.tab1)
        self.label_39.setGeometry(QtCore.QRect(760, 659, 381, 41))
        self.label_39.setStyleSheet("background:rgb(150,150,150,100);\n"
                                    "border:none;\n"
                                    "color:red;\n"
                                    "font: 75 10pt \"MS Shell Dlg 2\";\n"
                                    "border-radius:15%;")
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("city-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.addTab(self.tab1, icon1, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def upload(self):
        safe2=1
        safe = 1
        name = self.lineEdit_5.text()
        contact = self.lineEdit_6.text()
        if (len(contact) != 10 and type(contact != int)):
            # self.label_16.setText("enter 10 digit integer")
            safe2 = 0
        email_id = self.lineEdit_14.text()
        regex = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,7}\b'
        if re.fullmatch(regex, email_id):
            safe1 = 1
        else:
            safe1 = 0
        address_line_1 = self.lineEdit_4.text()
        address_line_2 = self.lineEdit_5.text()
        address_line_3 = self.lineEdit_6.text()
        emp_id = self.userID
        if len(name) != 0 and len(contact) != 0 and len(email_id) != 0 and len(
                address_line_1 + address_line_2 + address_line_3) != 0 and safe == 1 and safe1==1 and safe2==1:
            try:
                mydb = mc.connect(
                    host="localhost",
                    user="root",
                    password="Yash@2914",
                    database="dbms_project"
                )
                query_add_seller = "INSERT INTO seller (emp_id,name,email_id,contact,address_line_1,address_line_2,address_line_3) VALUES (%s, %s, %s, %s,%s,%s,%s)"
                value = (emp_id, name, email_id, contact, address_line_1, address_line_2, address_line_3)
                cursor = mydb.cursor()
                cursor.execute(query_add_seller, value)

                seller_id = cursor.lastrowid
                # Connect the currentIndexChanged signal to the onActivated method

                mode = ""
                if self.radioButton_4.isChecked():
                    mode = "S"
                if self.radioButton_5.isChecked():
                    mode = "R"
                if self.radioButton_6.isChecked():
                    mode = "SR"

                address_line_1 = self.lineEdit_9.text()
                address_line_2 = self.lineEdit_10.text()
                address_line_3 = self.lineEdit_11.text()
                if mode == 'S':
                    self.lineEdit_3.setText('0')
                    self.lineEdit_3.setReadOnly(True)
                    # renting_price = self.lineEdit_3.text()
                    # renting_price = 0

                renting_price = self.lineEdit_3.text()
                onlyInt = QIntValidator()
                self.lineEdit_3.setValidator(onlyInt)
                if mode == 'R':
                    self.lineEdit_12.setText('0')
                    self.lineEdit_12.setReadOnly(True)
                    # selling_price = self.lineEdit_3.text()
                    # selling_price = 0

                selling_price = self.lineEdit_12.text()
                onlyInt = QIntValidator()
                self.lineEdit_12.setValidator(onlyInt)
                # try:
                #     number = int()
                # except Exception:
                #     QtGui.QMessageBox.about(self, 'Error', 'Input can only be a number')
                #     pass

                size = self.lineEdit_19.text()
                onlyInt = QIntValidator()
                self.lineEdit_19.setValidator(onlyInt)
                # isInt = 1
                # if type(size) != int:
                #     isInt = 0
                self.lineEdit_21.setText(str(date1.today()))
                self.lineEdit_21.setReadOnly(True)
                date = self.lineEdit_21.text()
                p_type = self.lineEdit_4.text()
                print(len(name))
                print(len(contact))
                print(len(mode))
                print(len(email_id))
                print(len(address_line_1))
                print(len(date))
                print(len(size))
                print(len(p_type))
                print(len(renting_price))
                print(len(selling_price))
                print(renting_price)
                print(selling_price)
                print(safe)
                # print(isInt)
                if len(name) != 0 and len(contact) != 0 and len(mode) != 0 and len(email_id) != 0 and len(
                        address_line_1 + address_line_2 + address_line_3) != 0 and safe == 1 and len(date) != 0 and len(
                    p_type) != 0 and len(size) != 0 and len(renting_price) != 0 and len(selling_price) != 0 :  # isInt == 1and isInt == 1
                    query_add_property = "INSERT INTO property (seller_id,date_of_reg,address_line_1,address_line_2,address_line_3,mode,renting_price,selling_price,year_of_construction,size,p_type) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"
                    values = (
                        seller_id,
                        date,
                        address_line_1,
                        address_line_2,
                        address_line_3,
                        mode,
                        int(renting_price),
                        int(selling_price),
                        int(year),
                        size,
                        p_type,
                    )
                    cursor.execute(query_add_property, values)

                    if cursor.rowcount > 0:

                        self.label_39.setText("Registration Successfull!")
                    else:

                        self.label_39.setText("Try again!")
                    mydb.commit()

                else:
                    self.label_39.setText("Enter all valid entries in property!")
                    # if(isInt == 1):
                    #         self.label_39.setText("Invalid Entries! Size must be a Integer")


            except mc.Error as e:
                traceback.print_exc()
                self.label_39.setText("enter valid entries!")
        else:
            self.label_39.setText("Enter all valid entries in seller!")

    def onActivated(self, index):
        # Get the selected item and display it in the label
        text = self.comboBox_2.itemText(index)
        self.label.setText(text)

        def modify_year(text):
            global year
            year = text

        modify_year(text)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "TabWidget"))
        self.lineEdit.setText(_translate("TabWidget", "  Respond to Tenant"))
        self.lineEdit_2.setText(_translate("TabWidget", "    Connect with "))
        self.label_5.setText(_translate("TabWidget", "SELL OR RENT YOUR PROPERTY"))
        self.label_6.setText(_translate("TabWidget", "You are posting this property for "))
        self.label_7.setText(_translate("TabWidget", "FREE"))
        self.label_11.setText(_translate("TabWidget", " Enter yourWhatsApp No. to get enquiries"))
        self.label_12.setText(_translate("TabWidget", "            from Buyers / Tenants."))
        self.commandLinkButton.setText(_translate("TabWidget", "Back to Login"))
        self.label_18.setText(_translate("TabWidget", "How to find the right Tenant?"))
        self.label_21.setText(_translate("TabWidget", "Enquiries"))
        self.label_22.setText(_translate("TabWidget", "Matched Tenants"))
        self.label_41.setText(_translate("TabWidget", "Name"))
        self.label_10.setText(_translate("TabWidget", "Mobile"))
        self.comboBox.setItemText(0, _translate("TabWidget", "IND +91"))
        self.label_13.setText(_translate("TabWidget", "Email-Id"))
        self.label_14.setText(_translate("TabWidget", "Address"))
        self.label_42.setText(_translate("TabWidget", "Street"))
        self.label_43.setText(_translate("TabWidget", "Area"))
        self.label_44.setText(_translate("TabWidget", "Part Of Delhi"))
        self.label_8.setText(_translate("TabWidget",
                                        "                                                                  PERSONAL DETAILS"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "SELLER"))
        self.label_25.setText(_translate("TabWidget", "100% complete listing gets you more leads"))
        self.lineEdit_7.setText(_translate("TabWidget", "Listing Completeness"))
        self.lineEdit_8.setText(
            _translate("TabWidget", "                                            UPLOAD PROPERTY DETAILS"))
        self.pushButton_4.setText(_translate("TabWidget", "Apartment"))
        self.pushButton_5.setText(_translate("TabWidget", "Independent Floor"))
        self.pushButton_6.setText(_translate("TabWidget", "Others"))
        self.pushButton_7.setText(_translate("TabWidget", "Independent House"))
        self.pushButton_8.setText(_translate("TabWidget", "Villa"))
        self.pushButton_9.setText(_translate("TabWidget", "1-3 BHK"))
        self.pushButton_11.setText(_translate("TabWidget", "sq feets"))
        self.lineEdit_9.setPlaceholderText(_translate("TabWidget", "street"))
        self.lineEdit_10.setPlaceholderText(_translate("TabWidget", "area"))
        self.lineEdit_11.setPlaceholderText(_translate("TabWidget", "part of Delhi"))
        self.comboBox_2.setItemText(0, _translate("TabWidget", "2001"))
        self.comboBox_2.setItemText(1, _translate("TabWidget", "2002"))
        self.comboBox_2.setItemText(2, _translate("TabWidget", "2003"))
        self.comboBox_2.setItemText(3, _translate("TabWidget", "2004"))
        self.comboBox_2.setItemText(4, _translate("TabWidget", "2005"))
        self.comboBox_2.setItemText(5, _translate("TabWidget", "2006"))
        self.comboBox_2.setItemText(6, _translate("TabWidget", "2007"))
        self.comboBox_2.setItemText(7, _translate("TabWidget", "2008"))
        self.comboBox_2.setItemText(8, _translate("TabWidget", "2009"))
        self.comboBox_2.setItemText(9, _translate("TabWidget", "2010"))
        self.comboBox_2.setItemText(10, _translate("TabWidget", "2011"))
        self.comboBox_2.setItemText(11, _translate("TabWidget", "2012"))
        self.comboBox_2.setItemText(12, _translate("TabWidget", "2013"))
        self.comboBox_2.setItemText(13, _translate("TabWidget", "2014"))
        self.comboBox_2.setItemText(14, _translate("TabWidget", "2015"))
        self.comboBox_2.setItemText(15, _translate("TabWidget", "2016"))
        self.comboBox_2.setItemText(16, _translate("TabWidget", "2017"))
        self.comboBox_2.setItemText(17, _translate("TabWidget", "2018"))
        self.comboBox_2.setItemText(18, _translate("TabWidget", "2019"))
        self.comboBox_2.setItemText(19, _translate("TabWidget", "2020"))
        self.comboBox_2.setItemText(20, _translate("TabWidget", "2021"))
        self.comboBox_2.setItemText(21, _translate("TabWidget", "2022"))
        self.comboBox_2.setItemText(22, _translate("TabWidget", "2023"))
        self.lineEdit_12.setPlaceholderText(_translate("TabWidget", "selling price"))
        self.label_28.setText(_translate("TabWidget", "I want to.."))
        self.label_29.setText(_translate("TabWidget", "Property type"))
        self.label_30.setText(_translate("TabWidget", "Size"))
        self.label_31.setText(_translate("TabWidget", "Year of Construction"))
        self.label_32.setText(_translate("TabWidget", "Street"))
        self.label_33.setText(_translate("TabWidget", "Area"))
        self.label_34.setText(_translate("TabWidget", "Part of DELHI"))
        self.pushButton_14.setText(_translate("TabWidget", "UPLOAD"))
        self.label_35.setText(_translate("TabWidget", "COST"))
        self.label_36.setText(_translate("TabWidget", "Address:"))
        self.label_37.setText(_translate("TabWidget", "l"))
        self.radioButton_4.setText(_translate("TabWidget", "SELL"))
        self.radioButton_5.setText(_translate("TabWidget", "RENT"))
        self.radioButton_6.setText(_translate("TabWidget", "BOTH"))
        self.lineEdit_3.setPlaceholderText(_translate("TabWidget", "renting price"))
        self.label_48.setText(_translate("TabWidget", "Date of registration"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "PROPERTY"))


import form_rc
import res_rc

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     TabWidget = QtWidgets.QTabWidget()
#     ui = seller_TabWidget()
#     ui.setupUi(TabWidget)
#     TabWidget.show()
#     sys.exit(app.exec_())
