# -*- coding: utf-8 -*-
import subprocess
import traceback

# Form implementation generated from reading ui file 'PropertyNetworks.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
import mysql.connector as mc
import frame2

class Ui_QmainWindow(object):
    def setupUi(self, QmainWindow):
        QmainWindow.setObjectName("QmainWindow")
        QmainWindow.resize(1267, 939)
        QmainWindow.setStyleSheet("*{\n"
"font-family: century gothic;\n"
"font-size:24px;\n"
"}\n"
"QFrame\n"
"{\n"
"background:rgba(0,0,0,0.8);\n"
"border-radius:15px;\n"
"}\n"
"#form\n"
"{\n"
"border-image:url(:/images/background.jpg);\n"
"}\n"
"QPushButton\n"
"{\n"
"background:#af69ee;\n"
"border-radius:60px;\n"
"}\n"
"QToolButton\n"
"{\n"
"background:#af69ee;\n"
"border-radius:60px;\n"
"}\n"
"QToolButton:hover\n"
"{\n"
"background:#470787;\n"
"border-radius:60px;\n"
"}\n"
"QLabel\n"
"{\n"
"color:white;\n"
"background:transparent;\n"
"}\n"
"QPushButton\n"
"{\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:#49ebff;\n"
"color:#333;\n"
"border-radius:15px;\n"
"}\n"
"QLineEdit\n"
"{\n"
"background:transparent;\n"
"border:none;\n"
"color:#717072;\n"
"border-bottom:1px solid #717072;\n"
"}\n"
"")
        self.form = QtWidgets.QWidget(QmainWindow)
        self.form.setAutoFillBackground(False)
        self.form.setObjectName("form")
        self.frame = QtWidgets.QFrame(self.form)
        self.frame.setGeometry(QtCore.QRect(380, 150, 511, 611))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Label = QtWidgets.QLabel(self.frame)
        self.Label.setGeometry(QtCore.QRect(190, 70, 141, 61))
        self.Label.setStyleSheet("")
        self.Label.setObjectName("Label")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(150, 500, 221, 51))
        self.pushButton.setObjectName("pushButton")



        self.LineEdit = QtWidgets.QLineEdit(self.frame)
        self.LineEdit.setGeometry(QtCore.QRect(50, 260, 421, 41))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.LineEdit_2.setGeometry(QtCore.QRect(50, 390, 421, 41))
        self.LineEdit_2.setText("")
        self.LineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 200, 201, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 330, 191, 41))
        self.label_2.setObjectName("label_2")

        self.label_result = QtWidgets.QLabel(self.frame)
        self.label_result.setGeometry(QtCore.QRect(160, 560, 201, 20))
        self.label_result.setStyleSheet("color:red;")
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")

        self.toolButton = QtWidgets.QToolButton(self.form)
        self.toolButton.setGeometry(QtCore.QRect(580, 90, 121, 121))
        self.toolButton.setSizeIncrement(QtCore.QSize(7, 0))
        self.toolButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/user-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(128, 64))
        self.toolButton.setObjectName("toolButton")
        QmainWindow.setCentralWidget(self.form)
        self.menubar = QtWidgets.QMenuBar(QmainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1267, 36))
        self.menubar.setObjectName("menubar")
        QmainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(QmainWindow)
        self.statusbar.setObjectName("statusbar")
        QmainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QmainWindow)
        QtCore.QMetaObject.connectSlotsByName(QmainWindow)



    def retranslateUi(self, QmainWindow):
        _translate = QtCore.QCoreApplication.translate
        QmainWindow.setWindowTitle(_translate("QmainWindow", "MainWindow"))
        self.Label.setText(_translate("QmainWindow", "LOGIN HERE"))
        self.pushButton.setText(_translate("QmainWindow", "SUBMIT"))
        self.LineEdit.setText(_translate("QmainWindow", "UserID"))
        self.LineEdit.setPlaceholderText(_translate("QmainWindow", "UserID"))
        self.LineEdit_2.setPlaceholderText(_translate("QmainWindow", "Password"))
        self.label.setText(_translate("QmainWindow", "UserID"))
        self.label_2.setText(_translate("QmainWindow", "Password"))
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QmainWindow = QtWidgets.QMainWindow()
    ui = Ui_QmainWindow()
    ui.setupUi(QmainWindow)
    QmainWindow.show()
    sys.exit(app.exec_())
