# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'property_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
import traceback

from PyQt5.QtWidgets import QTableWidgetItem


class Property_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1279, 556)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 1281, 561))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/background.jpeg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.sold_2 = QtWidgets.QTabWidget(Dialog)
        self.sold_2.setGeometry(QtCore.QRect(90, 160, 1131, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sold_2.setFont(font)
        self.sold_2.setStyleSheet("background-color: rgb(213, 213, 213);")
        self.sold_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.sold_2.setObjectName("sold_2")
        self.Available = QtWidgets.QWidget()
        self.Available.setObjectName("Available")
        self.tableWidget = QtWidgets.QTableWidget(self.Available)
        self.tableWidget.setGeometry(QtCore.QRect(-10, -9, 1141, 291))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icons8-list-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sold_2.addTab(self.Available, icon, "")
        self.sold = QtWidgets.QWidget()
        self.sold.setObjectName("sold")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.sold)
        self.tableWidget_2.setGeometry(QtCore.QRect(-5, -9, 1131, 281))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(9)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(130)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/house-user-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sold_2.addTab(self.sold, icon1, "")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 80, 781, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"background:rgb(225, 225, 225,100);\n"
"border:none;\n"
"color:#717072;\n"
"border-radius:15%;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1100, 90, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton\n"
"{\n"
"background:#af69ee;\n"
"border-radius:60px;\n"
"color:white;\n"
"border-radius:15px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:#49ebff;\n"
"color:#333;\n"
"border-radius:15px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(720, 90, 361, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        self.sold_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)



    def property(self):
            # self.ui = Agentoffice_MainWindow()
            area = str(self.lineEdit.text())
            print(area)  # input
            try:
                    mydb = mc.connect(
                            host="localhost",
                            user="root",
                            password="Yash@2914",
                            database="dbms_project"
                    )
                    cursor = mydb.cursor()
                    query = "SELECT p.p_id, p.p_type,p.size, p.Address_line_1, p.Address_line_2, Address_line_3, p.selling_price, p.renting_price from property as p where (mode like 'S' or mode like 'R' or mode like 'SR') and Address_line_3 like '" + area + "'"
                    query2 = "SELECT p.p_id, st.buyer_id, p.p_type, p.address_line_1, p.address_line_2, p.address_line_3, st.date, p.price , p.mode from property as p join status as st where p.p_id=st.p_id and Address_line_3 like '" + area + "'"
                    cursor.execute(query)
                    result = cursor.fetchall()
                    self.tableWidget.setRowCount(0)
                    for row_Number, row_data in enumerate(result):
                            self.tableWidget.insertRow(row_Number)
                            for column_Number, data in enumerate(row_data):
                                    self.tableWidget.setItem(row_Number, column_Number, QTableWidgetItem(str(data)))
                    cursor.execute(query2)
                    result2 = cursor.fetchall()
                    self.tableWidget_2.setRowCount(0)
                    for row_Number, row_data in enumerate(result2):
                            self.tableWidget_2.insertRow(row_Number)
                            for column_Number, data in enumerate(row_data):
                                    self.tableWidget_2.setItem(row_Number, column_Number, QTableWidgetItem(str(data)))


            except mc.Error as e:
                    traceback.print_exc()


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "P_id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "P_type"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Size"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Address line 1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Address line 2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Address line 3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Selling Price"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Renting Price"))
        self.sold_2.setTabText(self.sold_2.indexOf(self.Available), _translate("Dialog", "AVAILABLE"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "P_id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "B_id"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "P_type"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Address line 1"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Address line 2"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Address line 3"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Date of sell"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Price"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Mode"))
        self.sold_2.setTabText(self.sold_2.indexOf(self.sold), _translate("Dialog", "SOLD/RENTED"))
        self.label_2.setText(_translate("Dialog", "Enter the area of Delhi : "))
        self.pushButton.setText(_translate("Dialog", "Submit"))
import form_rc
import res_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Property_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
